In [154]:
import numpy as np
import pandas as pd

In [155]:
# input_file = 'input_1.txt'
input_file = 'test_input_1.txt'

In [156]:
with open(file=input_file, mode='r') as file:
    lines = []

    for line in file:
        lines.append(list(line.strip()))

In [157]:
nodes = []
starting_node_found = False
starting_node = None

m = len(lines)

for i in range(m):
    n = len(lines[i])

    for j in range(n):
        current_val = lines[i][j]

        if current_val != '#':
            nodes.append(
                (i, j)
            )

            if not starting_node_found and current_val == 'S':
                starting_node = (i, j)
                starting_node_found = True

nodes.sort()

In [158]:
A = pd.DataFrame(data=0, columns=nodes, index=nodes)

In [159]:
for node in nodes:
    node_right = (node[0], node[1] + 1)
    node_below = (node[0] + 1, node[1])

    if node_right in nodes:
        A.at[node, node_right] = 1
        A.at[node_right, node] = 1

    if node_below in nodes:
        A.at[node, node_below] = 1
        A.at[node_below, node] = 1

In [160]:
A

,"(0, 0)","(0, 1)","(0, 2)","(0, 3)","(0, 4)","(0, 5)","(0, 6)","(0, 7)","(0, 8)","(0, 9)",...,"(10, 1)","(10, 2)","(10, 3)","(10, 4)","(10, 5)","(10, 6)","(10, 7)","(10, 8)","(10, 9)","(10, 10)"
"(0, 0)",0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"(0, 1)",1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"(0, 2)",0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"(0, 3)",0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"(0, 4)",0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(10, 6)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
"(10, 7)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
"(10, 8)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
"(10, 9)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
"(10, 10)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [161]:
number_of_steps = 64
current_nodes = [starting_node]

for step in range(number_of_steps):
    new_current_nodes = set()

    for current_node in current_nodes:
        new_current_nodes.update(set((A.loc[A[current_node] > 0]).index))

    current_nodes = list(new_current_nodes)

len(current_nodes)

42